name: Build and publish docker images
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  UV_VERSION: 0.9
  PYTHON_VERSION: 3.12
  JUPYTER_VERSION: 2025-04-14
  NORTH_TOOL_DIR: src/{{cookiecutter.module_name}}/north_tools/{{cookiecutter.north_tool_name}}

permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write

jobs:
  build:
    name: Build Jupyter Image
    runs-on: ubuntu-latest
    outputs:
      tags: {% raw %}${{ steps.meta.outputs.tags }}{% endraw %} # list
      labels: {% raw %}${{ steps.meta.outputs.labels }}{% endraw %} # list
    steps:
      - uses: actions/checkout@v4
        with:
          ref: {% raw %}${{ github.head_ref || github.ref_name }}{% endraw %}
          fetch-depth: 0
          show-progress: true
          submodules: true

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: {% raw %}${{ env.PYTHON_VERSION }}{% endraw %}
          version: {% raw %}${{ env.UV_VERSION }}{% endraw %}

      - name: Check Jupyter Requirements
        run: |
          {% raw %}uv pip compile pyproject.toml --group north -o requirements.txt
          if [[ `git diff requirements.txt` ]]; then
            echo "requirements.txt is not up to date. Please run 'uv pip compile pyproject.toml --group north -o requirements.txt --python ${{ env.PYTHON_VERSION }}' and commit the changes."
            exit 1
          fi{% endraw %}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: {% raw %}${{ env.REGISTRY }}{% endraw %}
          username: {% raw %}${{ github.actor }}{% endraw %}
          password: {% raw %}${{ secrets.GITHUB_TOKEN}}{% endraw %}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: {% raw %}${{ env.REGISTRY }}/${{ github.repository }}{% endraw %}
          # set latest tag for main branch and tags
          # https://github.com/docker/metadata-action?tab=readme-ov-file#image-name-and-tag-sanitization
          tags: |
            {% raw %}type=ref,event=tag
            type=ref,event=pr,{{branch}}-
            type=raw,value=main,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}{% endraw %}
          flavor: |
            latest=auto

      # https://docs.docker.com/build/ci/github-actions/share-image-jobs/
      # https://github.com/docker/build-push-action
      - name: Build and publish Jupyter image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: {% raw %}${{ env.NORTH_TOOL_DIR }}{% endraw %}/Dockerfile
          build-args: |
            {% raw %}UV_VERSION=${{ env.UV_VERSION }}
            JUPYTER_VERSION=${{ env.JUPYTER_VERSION }}{% endraw %}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: {% raw %}${{ steps.meta.outputs.tags }}{% endraw %}
          labels: {% raw %}${{ steps.meta.outputs.labels }}{% endraw %}