name: Upload Python Package

on:
  release:
    types: [published]

env:
  PYTHON_VERSION: 3.12{% if cookiecutter.include_north_tools %}
  IMAGE: "ghcr.io/{{cookiecutter.github_username|lower}}/{{cookiecutter.plugin_name}}"
{% endif %}
jobs:
  {% if cookiecutter.include_north_tools %}build-docker-image:
    uses: ./.github/workflows/publish_north.yml
    secrets: inherit
{% endif %}
  build:
    name: Build Package
    runs-on: ubuntu-latest
    {% if cookiecutter.include_north_tools %}needs: build-docker-image{% endif %}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install uv and set the Python version to {% raw %}${{ env.PYTHON_VERSION }}{% endraw %}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: {% raw %}${{ env.PYTHON_VERSION }}{% endraw %}
      {% if cookiecutter.include_north_tools %}- name: Overwrite the image tag
        run: |
          {% raw %}IMAGE_TAG=$(grep -oP "${{ env.IMAGE }}:\K[^'\",]+" {% endraw %}src/{{cookiecutter.module_name}}/north_tools/__init__.py)

          {% raw %}sed -i "s|${{ env.IMAGE }}:${IMAGE_TAG}|${{ env.IMAGE }}:${GITHUB_REF_NAME}|g" \{% endraw %}
          src/{{cookiecutter.module_name}}/north_tools/__init__.py
      {% endif %}
      - name: build package
        run: |
          uv build
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/

  {if cookiecutter.include_citation_file %}cff-version-check:
    name: Check cff-version
    runs-on: ubuntu-latest
    outputs:
      git_tag_version: {% raw %}${{ steps.git_tag_version.outputs.version }}{% endraw %}
      citation_version: {% raw %}${{ steps.citation_version.outputs.version }}{% endraw %}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install uv and set the python version to {% raw %}${{ env.python-version }}{% endraw %}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: {% raw %}${{ env.python-version }}{% endraw %}
      - name: Git tag version
        id: git_tag_version
        run: |
          GIT_TAG_VERSION={%raw%}${GITHUB_REF#refs/tags/v}{%endraw%}
          echo "version=$GIT_TAG_VERSION" >> "$GITHUB_OUTPUT"
      - name: Citation version
        id: citation_version
        run: |
          CITATION_VERSION=$(grep '^version:' CITATION.cff | cut -d' ' -f2)
          echo "version=$CITATION_VERSION" >> "$GITHUB_OUTPUT"

      - name: Fail if versions mismatch
        run: |
        {% raw %}if [ "${{ steps.git_tag_version.outputs.version }}" != "${{ steps.citation_version.outputs.version }}" ]; then
            echo "Version mismatch: Git tag is ${{ steps.git_tag_version.outputs.version }}, CITATION.cff is ${{ steps.citation_version.outputs.version }}"
            exit 1
          fi{% endraw %}{% endif %}

  # deploy:
  #   name: Upload to PyPI
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/p/{{cookiecutter.plugin_name}}
  #   permissions:
  #     id-token: write
  #   steps:
  #     - name: Download dist artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: dist-artifacts
  #         path: dist/
  #     - name: Publish package distributions to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
