name: Upload Python Package

on:
  release:
    types: [published]

env:
  PYTHON_VERSION: 3.12

jobs:
  {% if cookiecutter.include_north_tools %}build-docker-image:
    uses: ./.github/workflows/publish_north.yml
    secrets: inherit
{% endif %}
  build:
    name: Build Package
    runs-on: ubuntu-latest
    {% if cookiecutter.include_north_tools %}needs: build-docker-image{% endif %}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install uv and set the Python version to {% raw %}${{ env.PYTHON_VERSION }}{% endraw %}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: {% raw %}${{ env.PYTHON_VERSION }}{% endraw %}
      {% if cookiecutter.include_north_tools %}- name: Overwrite the image tag
        run: |
          {% raw %}IMAGE_TAG=$(grep -oP "${{ env.IMAGE }}:\K[^'\",]+" {% endraw %}src/{{cookiecutter.module_name}}/north_tools/{{cookiecutter.north_tool_name}}/__init__.py)

          {% raw %}sed -i "s|${{ env.IMAGE }}:${IMAGE_TAG}|${{ env.IMAGE }}:${GITHUB_REF_NAME}|g" \{% endraw %}
          src/{{cookiecutter.module_name}}/north_tools/{{cookiecutter.north_tool_name}}/__init__.py
      {% endif %}
      - name: build package
        run: |
          uv build
      {% if cookiecutter.include_north_tools %}- name: Check the image tag in the entry point
        run: |
          # unzip the built package and check the image tag in the entry point
          tar -xzf dist/*.tar.gz -C dist/
          IMAGE_TAG={% raw %}$(grep -oP "${{ env.IMAGE }}:\K[^'\",]+" {% endraw %}dist/{{cookiecutter.module_name}}-*/src/{{cookiecutter.module_name}}/north_tools/{{cookiecutter.north_tool_name}}/__init__.py)
          {% raw %}
          if [[ "${IMAGE_TAG}" == "${GITHUB_REF_NAME}" ]]; then
            echo "Before building the Python package, image ${{ env.IMAGE }}:${GITHUB_REF_NAME} is updated for NORTH tool."
          else
            echo "Error: Image tag in __init__.py is not correct: ${IMAGE_TAG}. Expected: ${{ env.IMAGE }}:${GITHUB_REF_NAME}"
            exit 1
          fi
          {% endraw %}
          # Remove the unzipped package after checking
          rm -rf dist/{{cookiecutter.module_name}}-*/
        {% endif %}
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/

  # deploy:
  #   name: Upload to PyPI
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/p/{{cookiecutter.plugin_name}}
  #   permissions:
  #     id-token: write
  #   steps:
  #     - name: Download dist artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: dist-artifacts
  #         path: dist/
  #     - name: Publish package distributions to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
