ARG IMAGE_TAG=main
ARG BASE_IMAGE=ghcr.io/fairmat-nfdi/nomad-north-jupyter
ARG PLUGIN_NAME={{cookiecutter.plugin_name}}

FROM ${BASE_IMAGE}:${IMAGE_TAG} AS base

# Base image may also come from nomad-north-jupyter at https://github.com/FAIRmat-NFDI/nomad-north-jupyter
# e.g., ghcr.io/fairmat-nfdi/nomad-north-jupyter:main
# Please check for details of the base image and Dockerfile at https://github.com/FAIRmat-NFDI/nomad-north-jupyter

# Or base image may also come from nomad-north-desktop-base at https://github.com/FAIRmat-NFDI/nomad-north-desktop-base
# e.g., ghcr.io/fairmat-nfdi/nomad-north-desktop-base:main
# Please check for details of the base image and Dockerfile at https://github.com/FAIRmat-NFDI/nomad-north-desktop-base
